apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
name: macvlan-ens224
namespace: igor
spec:
  config: '{"cniVersion": "0.3.1", "name": "macvlan-net224", "type": "macvlan", "master": "ens224", "mode": "bridge", "ipam": {"type": "static", "routes": [ {  "dst": "192.168.32.0/24", "gateway": "192.168.32.1" } ], "gateway": "192.168.32.1", "capabilities": { "mac": true } } }'
