apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: localnet-mapping
spec:
  desiredState:
    ovn:
      bridge-mappings:
        - bridge: ovs-br224
          localnet: localnet-192.168.0
          state: present
        - bridge: br-ex
          localnet: localnet-172.16.103
          state: present
        - bridge: ovs-br224
          localnet: localnet-vlan150
          state: present

#---------------NAD---------
spec:
  config: |-
    {
        "cniVersion": "0.4.0",
        "name": "mgmt-10-15-45",
        "type": "ovn-k8s-cni-overlay",
        "netAttachDefName": "default/mgmt-10-15-45",
        "topology": "localnet"
    }
